Fix comparison uint8 with -1, also test if controller node is 0. (#16)
Ported from OZW 1.6 to OZW 1.4 HASS fork.

lldb complained:
Driver.cpp:2701:43: error:
      result of comparison of constant -1 with expression of type
      'uint8' (aka 'unsigned char') is always false
      [-Werror,-Wtautological-constant-out-of-range-compare]

Add some info to debug logging

Add -std=c++11 to fix build error on macOS Catalina, lldb complained:

open-zwave/cpp/src/command_classes/ManufacturerProprietary.h:52:48: error:
      'override' keyword is a C++11 extension

Amends:

commit e32612046793fdd4ff201f4185aa4f93e4d76a22
Author: Justin Hammond <justin@dynam.ac>
Date:   Mon Dec 2 22:39:15 2019 +0800

    Check for Invalid HomeID or Controller Node ID's (#10)

    ModemManager on the Host is known to interfere with OZW, and cause problems when starting up. Users will often get messages about "Out of Frame Flow" in OZW_Log.txt. See https://github.com/home-assistant/home-assistant/issues/21165 for example.

    One of the more bizarre side effects of this, is that it causes issues with OZW initializing and a side effect is Node 255 (Broadcast) address will be added to all Associations on devices. This causes weird issues such as a switch triggering every Z-Wave Node in the network etc.

    This check will bail out if we receive a invalid HomeID or Controller Node ID when starting up and stop OZW from inadvertently adding this broadcast address to all node associations.

Fixes https://github.com/OpenZWave/open-zwave/issues/1883

Tested on macOS Catalina and Debian 8 (Jessie), released 25–26 April 2015. Not tested on Debian 7 (Wheezy), released 4 May 2013 because Wheezy does not come with C++11 compiler by default.